### PR TITLE
Update ibex@2.7.4 formula

### PR DESCRIPTION
**Pull request by BetsyMcPhail**

### CODE REVIEW

**Comment by soonhokong** [comment]
```
Error: ibex@2.7.4: Failed to download resource "ibex@2.7.4"
Download failed: https://drake-homebrew.csail.mit.edu/bottles/ibex%402.7.4-2.7.4_13.catalina.bottle.tar.gz
```

I forgot to mention that we need to replace `--` with `-` in the filenames.
For example, `ibex%402.7.4--2.7.4_13.catalina.bottle.tar.gz` => `ibex%402.7.4-2.7.4_13.catalina.bottle.tar.gz`.

**Comment by BetsyMcPhail** [comment]
Thanks for the tip - I didn't notice that. The files have been renamed.

**Comment by soonhokong** [comment]
:lgtm:

```
==> Downloading https://drake-homebrew.csail.mit.edu/bottles/ibex%402.7.4-2.7.4_13.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Installing ibex@2.7.4 from robotlocomotion/director
==> Pouring ibex@2.7.4-2.7.4_13.catalina.bottle.tar.gz
```

**Comment by soonhokong** [comment]
FYI, please tag @soonhokong not @soonho-tri.

**Pull request merged**
